

services:

  app:
    build:
      context: ./node
      dockerfile: dockerfile
    image: felipesousagomes/node:latest
    container_name: app
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app:cached
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    image: felipesousagomes/nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
        - app


networks:
  node-network:
    driver: bridge
